version: '3.5'
services:
  db:
    image: mongo
    container_name: shadowban-db
    hostname: shadowban-db
    env_file:
      - ./env/mongod.env
    networks:
      - common

  www:
    build: www/.
    container_name: shadowban-www
    hostname: shadowban-www
    ports:
      - "${PUBLIC_IP}:80:80"
      - "${PUBLIC_IP}:443:443"
    volumes:
      # main config
      - ./www/nginx.conf:/etc/nginx/nginx.conf
      # site configs
      - ./www/sites-enabled:/etc/nginx/sites-enabled
      # document roots
      - ./sites:/var/sites
      # SSL certificates
      - ./www/ssl:/etc/nginx/ssl
      # log files
      - ./logs/nginx:/var/log/nginx
    networks:
      - common

  testing:
    build: ../testing/.
    container_name: shadowban-testing
    hostname: shadowban-testing
    command: ./bin/docker-entry.sh
    expose:
      - "${TESTING_PORT}"
    volumes:
      - ./logs/testing:/app/logs
    env_file:
      - ./env/testing.env
    depends_on:
      - db
      - www
    networks:
      - common

networks:
  common:
    name: shadowban-eu_common
