version: '3.5'
services:
  db:
    image: mongo
    container_name: shadowban-db
    hostname: shadowban-db
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - ./env/mongod.env
    networks:
      - common

  www:
    build: www/.
    container_name: shadowban-www
    hostname: shadowban-www
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      # main config
      - ./www/nginx.conf:/etc/nginx/nginx.conf
      # site configs
      - ./www/sites-enabled:/etc/nginx/sites-enabled
      # document roots
      - ./sites:/var/sites
      # SSL certificates
      - ./www/ssl:/etc/nginx/ssl
      # log files
      - ./logs/nginx:/var/log/nginx
    networks:
      - common

  testing:
    build: ../testing/.
    container_name: shadowban-testing
    hostname: shadowban-testing
    command: ./bin/docker-entry.sh
    stdin_open: true
    expose:
      - "4040"
    volumes:
      - ../testing:/app
      - ./logs/testing:/app/logs
    env_file:
      - ./env/testing.env
    depends_on:
      - db
      - www
    networks:
      - common

  timeline-termination:
    build: ../timeline-termination/.
    container_name: shadowban-timeline-termination
    hostname: shadowban-timeline-termination
    command: yarn dev
    stdin_open: true
    expose:
      - "3300"
    volumes:
      - ../timeline-termination:/app
      - ./logs/timeline-termination:/app/logs
    env_file:
      - ./env/timeline-termination.env
    depends_on:
      - db
      - www
    networks:
      - common

  pwa:
    build: ../pwa/.
    container_name: shadowban-pwa
    hostname: shadowban-pwa
    command: yarn start
    stdin_open: true
    expose:
      - "3000"
    volumes:
      - ../pwa:/app
    env_file:
      - ./env/pwa.env
    depends_on:
      - www
    networks:
      - common

networks:
  common:
    name: shadowban-dev_common
